version: "3.3"

services:
  app:
    container_name: "syncpos-be"
    build: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - JWT_KEY=secretkey
    command: npm start
volumes:
  node_modules:
